spring.application.name=sich-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/sich
spring.datasource.username=sich_user
spring.datasource.password=sich1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.flyway.enabled=false
spring.cache.type=simple

spring.banner.charset=UTF-8

server.port=4100
logging.level.org.hibernate.SQL=debug

# JWT — TROQUE o secret em produção (base64 com pelo menos 32 bytes decodificados)
app.security.jwt.secret=Y29sb2NhLXVtLXNlY3JldC1sb25nby1lLWFsZWF0b3Jpby1lbS1iYXNlNjQtY29tLXBlbG8tbWVub3MtMzItYnl0ZXM=
app.security.jwt.expiration-ms=3600000